sudo: false
# services:
#   - redis-server
addons:
  postgresql: "9.3"

language: python
python:
  - "2.7"
  - "3.4"

before_script:
    - psql -c 'create database djangobmf;' -U postgres
install:
    - pip install . django$DJANGO_VERSION
script:
    - python runtests.py -v2

env:
  - global:
    - DJANGO_SETTINGS_MODULE=sandbox.settings_travis
  - matrix:
    - DJANGO_VERSION=">1.8,<1.8.999"
    - DJANGO_VERSION="==1.9a1"

matrix:
    allow_failures:
        - env: DJANGO_VERSION=1.9a1

git:
    submodules: false
