sudo: false
# services:
#   - redis-server
# addons:
#   postgresql: "9.3"

language: python
python:
  - "2.7"
  - "3.4"

install:
  - pip install $DJANGO_VERSION $PIP_ADDITIONAL
  - pip install . 
  - pip install -rrequirements/develop.txt
  - pip install psycopg2 celery
script:
  - coverage run runtests.py -v2
  - coverage report -m --skip-covered

env:
  global:
    - DJANGO_SETTINGS_MODULE=sandbox.settings
    - PIP_ADDITIONAL=""
  matrix:
    - DJANGO_VERSION="django>1.8,<1.9"
    - DJANGO_VERSION=django==1.9 PIP_ADDITIONAL=https://github.com/ojii/django-sekizai/archive/master.zip#egg=sekizai
    - DJANGO_VERSION=django==1.9

matrix:
  fast_finish: true
  allow_failures:
    - env: DJANGO_VERSION=django==1.9
