language: python
install:
    - pip install tox 
script:
    - tox
env:
    - TOXENV=py27-1.8
    - TOXENV=py34-1.8
    - TOXENV=py27-1.9
    - TOXENV=py34-1.9
#   - TOXENV=py27-1.10
#   - TOXENV=py34-1.10
    - TOXENV=docs
matrix:
    allow_failures:
        - env: TOXENV=py27-1.9
        - env: TOXENV=py34-1.9
#       - env: TOXENV=py27-1.10
#       - env: TOXENV=py34-1.10
git:
    submodules: false
