sudo: false
# services:
#   - redis-server
# addons:
#   postgresql: "9.3"

language: python
python:
  - "2.7"
  - "3.4"

install:
  - pip install django$DJANGO_VERSION $PIP_ADDITIONAL
  - pip install . 
  - pip install -rrequirements/develop.txt
  - pip install psycopg2 celery
script:
  - python runtests.py -v2

env:
  global:
    - DJANGO_SETTINGS_MODULE=sandbox.settings_travis
    - PIP_ADDITIONAL=""
  matrix:
    - DJANGO_VERSION=">1.8,<1.8.999"
    - DJANGO_VERSION="==1.9a1"
    - DJANGO_VERSION="==1.9a1" PIP_ADDITIONAL="https://github.com/ojii/django-sekizai/archive/master.zip#egg=sekizai"

matrix:
  fast_finish: true
  allow_failures:
    - python: 2.7
      env: DJANGO_VERSION="==1.9a1"
    - python: 3.4
      env: DJANGO_VERSION="==1.9a1"
