language: python
install:
    - pip install tox 
script:
    - tox
env:
    - TOXENV=py27-1.7
    - TOXENV=py27-1.8
    - TOXENV=py33-1.7
    - TOXENV=py33-1.8
    - TOXENV=py34-1.7
    - TOXENV=py34-1.8
    - TOXENV=docs
