db:
  image: postgres

redis:
  image: redis

web:
  build: .
  command: /code/web.sh
  environment:
    - DJANGO_SETTINGS_MODULE=sandbox.settings_docker
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
    - redis

worker:
  build: .
  command: celery -A sandbox worker -l info -c 1 --autoreload
  environment:
    - DJANGO_SETTINGS_MODULE=sandbox.settings_docker
    - C_FORCE_ROOT=1
  volumes:
    - .:/code
  links:
    - db
    - redis
